//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4952.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public int userID { get; set; }
        public byte[] data { get; set; }
        public string fileName { get; set; }
        public int fileSize { get; set; }
        public System.DateTime fileDateCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
