
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _4952.Models
{

using System;
    using System.Collections.Generic;
    
public partial class File
{

    public int fileID { get; set; }

    public int userID { get; set; }

    public byte[] data { get; set; }

    public string fileName { get; set; }

    public string fileSize { get; set; }

    public string fileDateCreated { get; set; }



    public virtual User User { get; set; }

}

}
